# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_euler_active <- function(phi, theta, psi) {
    .Call('tmatrix_cpp_euler_active', PACKAGE = 'tmatrix', phi, theta, psi)
}

cpp_euler_passive <- function(phi, theta, psi) {
    .Call('tmatrix_cpp_euler_passive', PACKAGE = 'tmatrix', phi, theta, psi)
}

cpp_axis_rotation <- function(angle, axis) {
    .Call('tmatrix_cpp_axis_rotation', PACKAGE = 'tmatrix', angle, axis)
}

